services:
  - type: web
    name: oxam
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHONUNBUFFERED
        value: "1"
